basket = ["Banana", "Apples", "Oranges", "Blueberries"]
basket.remove("Banana")
print(basket)
basket.remove("Blueberries")
print(basket)
basket.append("Kiwi")
print(basket)
basket.insert(0,"apples")
print(basket)
Napple=basket.count("apple")
print(Napple)
basket.clear()
print(basket)
